/* ==========================================================================
   China Cheat Sheet — demo content
   内容遵循 docs/05-内容模板规范.md：
   - 英文主体，CEFR B1，单句 <= 15 词，步骤动词开头
   - 政策/支付类只写操作步骤，不做承诺，标注官方来源与更新时间

   多语言约定（重要，改动前先读这一段）：
   - 卡片里的 zh 是「递给中国人看的那句话」，是载荷，永不翻译。
     en / ja / ko 是给使用者自己看的释义。
   - 界面语言 = 中文 时，不显示释义（看的人本来就是中文使用者）。
   - 场景正文（steps / mistakes / planB / trouble / tip）目前只有 en。
     缺的语种由 app.js 的 L() 回落英文，并在页面顶部显示「翻译准备中」横幅。
     补翻译时直接在这些字段上加 ja / ko 键即可，横幅会自己消失。
   ========================================================================== */

/* 紧急电话：号码是全球通用的，只有名称需要翻译 */
const EMERGENCY_NUMBERS = [
  { num: "110", icon: "🚓", label: { en: "Police", zh: "报警", ja: "警察", ko: "경찰" } },
  { num: "120", icon: "🚑", label: { en: "Ambulance", zh: "急救", ja: "救急車", ko: "구급차" } },
  { num: "119", icon: "🚒", label: { en: "Fire", zh: "火警", ja: "消防", ko: "소방" } },
  { num: "122", icon: "🚗", label: { en: "Traffic", zh: "交通事故", ja: "交通事故", ko: "교통사고" } },
];

/* ==========================================================================
   界面文案 —— 按钮、标题这类「外壳」文字，按 key 查表
   ========================================================================== */

const UI = {
  en: {
    heroH1: "Your 3-minute guide to surviving daily life in China",
    heroP: "Not a travel guide. A step-by-step tool for the thing you need to do **right now**.",
    chipEnglishFirst: "English first",
    chipNoDownload: "No download",
    chipNoSignup: "No sign-up",
    chipOffline: "Works offline",
    searchPlaceholder: "Search: taxi, Alipay, 火车票, hotel…",
    wantTo: "I want to…",
    allHelpCards: "All help cards →",
    emergency: "Emergency",
    helpPage: "Help page →",
    beforeYouAsk: "Before you ask",
    allFaq: "All FAQ →",
    tip1t: "Cash is still the universal Plan B",
    tip1b: "Foreign cards fail at small vendors. Keep 200–500 yuan with you.",
    tip2t: "Your passport is also your ticket",
    tip2b: "Trains, hotels and many payments need it. Carry it, and keep a photo on your phone.",
    tip3t: "Ask the hotel front desk first",
    tip3b: "They can call, translate, book and write notes. It is their job to help guests.",
    footnote: "Content last reviewed 2026-09-23. Policy, payment and ticketing rules change — always confirm in the official app. This tool gives operating steps only, not legal, medical or financial advice.",
    task: "In short",
    onThisPage: "On this page",
    beforeYouStart: "Before you start",
    tipLabel: "💡 Tip",
    stepByStep: "Step by step",
    done: "done",
    steps: "steps",
    showThisScreen: "Show this screen",
    openFullScreen: "Open full screen 🗣️",
    usefulCards: "Useful Chinese cards",
    cards: "cards",
    commonMistakes: "Common mistakes",
    colMistake: "Mistake",
    colWhy: "Why it hurts",
    colDo: "Do this instead",
    planB: "Plan B — if the main path fails",
    trouble: "If something goes wrong",
    pleaseNote: "⚠️ Please note",
    officialSources: "Official sources: ",
    outdated: "This info is outdated",
    backToTasks: "Back to all tasks",
    show: "Show ›",
    helpCards: "Help cards",
    sets: "sets",
    howToUseCard: "How to use a card",
    howToUseCardB: "Tap any card to open it full screen. The Chinese is shown large — hand your phone to the person you are talking to. Tap **Hide English** if the English line distracts them.",
    howToUseCardC: "Sets are ordered from **most urgent to least urgent** — if you don't know where to look, start at the top.",
    faqTitle: "FAQ",
    faqNote: "Answers describe the common case. Rules change — confirm in the official app.",
    showThisToThem: "Show this to them",
    usefulCard: "useful card",
    hideEnglish: "Hide English",
    showEnglish: "Show English",
    copyZh: "Copy 中文",
    copied: "Copied ✓",
    copyFailed: "Copy failed — select manually",
    thanksLogged: "Thanks — logged for review",
    allStepsDone: "All steps done 🎉",
    matchingCards: "matching cards",
    noMatch: "No match. Try “taxi”, “payment”, “train” or a Chinese word like “火车”.",
    howToUse: "How to use",
    howToUseSub: "This app in 30 seconds",
    language: "Language",
    installApp: "Install app",
    installHint: "Choose “Install ChinaPASS” from your browser menu to add it to your home screen.",
    prepTitle: "Before you go",
    prepSub: "Do these before you fly. Each one removes a problem you would otherwise hit on arrival.",
    prepDone: "ready",
    prepAllDone: "All set — have a good trip.",
    prepNoteTitle: "Check current requirements",
    prepNoteBody: "Entry rules, payment support and app availability change. Confirm the details with official sources before you travel.",
    prepNoteLink: "Official travel services ↗",
    city: "City",
    cityTitle: "Where are you?",
    cityHint: "We use this to show local numbers and to build your location card. Your coordinates never leave your phone.",
    cityDetect: "Detect my city",
    cityDetecting: "Locating…",
    cityPick: "Or pick it yourself",
    cityNone: "Not set",
    citySet: "You're in",
    showLocationCard: "📍 Show my location card",
    locationNeedCity: "Set your city first",
    locationNeedsHttps: "Location needs a secure (https) connection. Pick your city instead.",
    locationDenied: "No location access. Pick your city instead.",
    aiTitle: "Ask AI",
    aiBody: "A chat that answers “what do I do now?” in your language. Not built yet.",
    aiCta: "Coming soon",
    onboardNext: "Next",
    onboardStart: "Start",
    onboardSkip: "Skip",
    partialNotice: "This page is not fully translated yet — showing English where needed.",
    partialShort: "some pages in English",
    back: "Back",
    close: "Close",
    settings: "Settings",
  },
  zh: {
    heroH1: "3 分钟搞定在中国的日常",
    heroP: "这不是旅游攻略。这是「**现在这一步该怎么做**」的分步工具。",
    chipEnglishFirst: "英文优先",
    chipNoDownload: "免下载",
    chipNoSignup: "免注册",
    chipOffline: "可离线",
    searchPlaceholder: "搜索：打车、支付宝、火车票、酒店…",
    wantTo: "我要做什么",
    allHelpCards: "全部求助卡片 →",
    emergency: "紧急",
    helpPage: "求助页 →",
    beforeYouAsk: "开口之前",
    allFaq: "全部常见问题 →",
    tip1t: "现金永远是最后的方案",
    tip1b: "外国卡在小商户常常刷不了。身上留 200–500 元。",
    tip2t: "护照就是你的车票",
    tip2b: "坐高铁、住酒店、很多支付都要用。随身带，手机里再存一张照片。",
    tip3t: "先问酒店前台",
    tip3b: "他们能打电话、翻译、代订、写便条。帮助客人本来就是他们的工作。",
    footnote: "内容最后核对于 2026-09-23。政策、支付和票务规则会变 —— 请以官方 App 为准。本工具只提供操作步骤，不构成法律、医疗或财务建议。",
    task: "简单说",
    onThisPage: "本页内容",
    beforeYouStart: "开始前准备",
    tipLabel: "💡 提示",
    stepByStep: "分步操作",
    done: "已完成",
    steps: "步",
    showThisScreen: "出示这一屏",
    openFullScreen: "全屏打开 🗣️",
    usefulCards: "中文求助卡片",
    cards: "张",
    commonMistakes: "常见错误",
    colMistake: "错误做法",
    colWhy: "为什么吃亏",
    colDo: "应该怎么做",
    planB: "备用方案 —— 主路径失败时",
    trouble: "如果出问题了",
    pleaseNote: "⚠️ 请注意",
    officialSources: "官方来源：",
    outdated: "这一页信息过期了",
    backToTasks: "返回全部任务",
    show: "出示 ›",
    helpCards: "求助卡片",
    sets: "组",
    howToUseCard: "卡片怎么用",
    howToUseCardB: "点任意一张卡片全屏打开。中文是大字 —— 把手机直接递给对方看。如果英文那行会干扰对方，点 **Hide English** 隐藏它。",
    howToUseCardC: "卡片组按**紧急程度从高到低**排列 —— 不知道看哪组就从最上面开始。",
    faqTitle: "常见问题",
    faqNote: "答案描述的是常见情况。规则会变 —— 请以官方 App 为准。",
    showThisToThem: "出示给对方",
    usefulCard: "求助卡片",
    hideEnglish: "隐藏英文",
    showEnglish: "显示英文",
    copyZh: "复制中文",
    copied: "已复制 ✓",
    copyFailed: "复制失败 —— 请手动选中",
    thanksLogged: "谢谢 —— 已记录待复核",
    allStepsDone: "全部步骤完成 🎉",
    matchingCards: "张匹配卡片",
    noMatch: "没有匹配。试试「打车」「支付」「火车」，或者英文关键词。",
    howToUse: "怎么用",
    howToUseSub: "30 秒看懂这个 App",
    language: "语言",
    installApp: "安装 App",
    installHint: "在浏览器菜单里选择「安装 ChinaPASS」，即可添加到主屏幕。",
    prepTitle: "行前准备",
    prepSub: "登机前做完这些。每一条都对应一个落地后会遇到的麻烦。",
    prepDone: "已完成",
    prepAllDone: "都准备好了，一路顺利。",
    prepNoteTitle: "出发前再核一次现行规定",
    prepNoteBody: "入境规定、支付支持情况和 app 可用性都会变。出发前请以官方渠道为准。",
    prepNoteLink: "官方旅行服务 ↗",
    city: "城市",
    cityTitle: "你在哪个城市？",
    cityHint: "用来显示当地信息和生成你的位置卡片。你的坐标不会离开这台手机。",
    cityDetect: "自动定位",
    cityDetecting: "定位中…",
    cityPick: "或手动选择",
    cityNone: "未设置",
    citySet: "你当前在",
    showLocationCard: "📍 出示我的位置卡片",
    locationNeedCity: "请先设置城市",
    locationNeedsHttps: "定位需要 https 安全连接。请手动选择城市。",
    locationDenied: "没有定位权限。请手动选择城市。",
    aiTitle: "问 AI",
    aiBody: "一个能用你的母语回答「我现在该做什么」的对话助手。还没做。",
    aiCta: "敬请期待",
    onboardNext: "下一步",
    onboardStart: "开始",
    onboardSkip: "跳过",
    partialNotice: "这一页还没有完成翻译 —— 缺失的部分显示英文。",
    partialShort: "部分页面为英文",
    back: "返回",
    close: "关闭",
    settings: "设置",
  },
  ja: {
    heroH1: "中国での毎日を3分で乗り切るガイド",
    heroP: "旅行ガイドではありません。「**今この瞬間に何をすべきか**」を示す手順ツールです。",
    chipEnglishFirst: "英語優先",
    chipNoDownload: "ダウンロード不要",
    chipNoSignup: "登録不要",
    chipOffline: "オフライン可",
    searchPlaceholder: "検索：タクシー、Alipay、切符、ホテル…",
    wantTo: "何をしたい？",
    allHelpCards: "すべてのカード →",
    emergency: "緊急",
    helpPage: "緊急ページ →",
    beforeYouAsk: "聞く前に",
    allFaq: "よくある質問 →",
    tip1t: "現金が最後の手段",
    tip1b: "小さい店では海外カードが使えないことが多いです。200〜500元を持ち歩きましょう。",
    tip2t: "パスポートが切符代わり",
    tip2b: "列車・ホテル・多くの支払いで必要です。常に携帯し、写真も残しておきましょう。",
    tip3t: "まずホテルのフロントへ",
    tip3b: "電話・翻訳・予約・メモ書きを頼めます。客を助けるのは彼らの仕事です。",
    footnote: "内容の最終確認日：2026-09-23。政策・決済・チケットの規則は変わります。必ず公式アプリで確認してください。本ツールは操作手順のみを提供し、法律・医療・財務上の助言は行いません。",
    task: "ひとことで言うと",
    onThisPage: "このページの内容",
    beforeYouStart: "事前準備",
    tipLabel: "💡 ヒント",
    stepByStep: "手順",
    done: "完了",
    steps: "ステップ",
    showThisScreen: "この画面を見せる",
    openFullScreen: "全画面で開く 🗣️",
    usefulCards: "中国語サポートカード",
    cards: "枚",
    commonMistakes: "よくある失敗",
    colMistake: "失敗",
    colWhy: "困ること",
    colDo: "こうする",
    planB: "代替案 — うまくいかないとき",
    trouble: "トラブルが起きたら",
    pleaseNote: "⚠️ ご注意",
    officialSources: "公式情報：",
    outdated: "この情報は古い",
    backToTasks: "タスク一覧に戻る",
    show: "見せる ›",
    helpCards: "サポートカード",
    sets: "セット",
    howToUseCard: "カードの使い方",
    howToUseCardB: "カードをタップすると全画面で開きます。中国語が大きく表示されるので、相手にスマホをそのまま渡してください。英語が邪魔なときは **Hide English** をタップ。",
    howToUseCardC: "セットは**緊急度の高い順**に並んでいます。どこを見ればいいか分からないときは上から順に。",
    faqTitle: "よくある質問",
    faqNote: "回答は一般的なケースです。規則は変わります — 公式アプリで確認してください。",
    showThisToThem: "相手に見せる",
    usefulCard: "サポートカード",
    hideEnglish: "英語を隠す",
    showEnglish: "英語を表示",
    copyZh: "中国語をコピー",
    copied: "コピーしました ✓",
    copyFailed: "コピー失敗 — 手動で選択してください",
    thanksLogged: "ありがとうございます — 記録しました",
    allStepsDone: "すべて完了 🎉",
    matchingCards: "件のカード",
    noMatch: "該当なし。「タクシー」「支払い」「電車」などで試してください。",
    howToUse: "使い方",
    howToUseSub: "30秒でわかる",
    language: "言語",
    installApp: "アプリをインストール",
    installHint: "ブラウザのメニューから「ChinaPASS をインストール」を選ぶと、ホーム画面に追加できます。",
    prepTitle: "出発前の準備",
    prepSub: "搭乗前に済ませておきましょう。どれも、到着後に困ることを一つずつ減らします。",
    prepDone: "完了",
    prepAllDone: "準備完了です。よい旅を。",
    prepNoteTitle: "最新の要件を確認",
    prepNoteBody: "入国規則・決済対応・アプリの提供状況は変わります。出発前に公式情報で確認してください。",
    prepNoteLink: "公式トラベルサービス ↗",
    city: "都市",
    cityTitle: "どの都市にいますか？",
    cityHint: "現地の情報と位置カードの作成に使います。座標がスマホの外に出ることはありません。",
    cityDetect: "現在地から判定",
    cityDetecting: "測位中…",
    cityPick: "または自分で選ぶ",
    cityNone: "未設定",
    citySet: "現在地",
    showLocationCard: "📍 位置カードを見せる",
    locationNeedCity: "先に都市を設定してください",
    locationNeedsHttps: "位置情報には https 接続が必要です。都市を選んでください。",
    locationDenied: "位置情報の権限がありません。都市を選んでください。",
    aiTitle: "AI に聞く",
    aiBody: "「今どうすればいい？」を母語で答えるチャット。まだ作っていません。",
    aiCta: "準備中",
    onboardNext: "次へ",
    onboardStart: "はじめる",
    onboardSkip: "スキップ",
    partialNotice: "このページはまだ翻訳が完了していません — 一部英語で表示します。",
    partialShort: "一部ページは英語",
    back: "戻る",
    close: "閉じる",
    settings: "設定",
  },
  ko: {
    heroH1: "중국 일상생활을 3분 안에 해결하는 가이드",
    heroP: "여행 가이드가 아닙니다. \"**지금 당장 무엇을 해야 하는지**\" 알려주는 단계별 도구입니다.",
    chipEnglishFirst: "영어 우선",
    chipNoDownload: "다운로드 불필요",
    chipNoSignup: "가입 불필요",
    chipOffline: "오프라인 가능",
    searchPlaceholder: "검색: 택시, 알리페이, 기차표, 호텔…",
    wantTo: "무엇을 하고 싶나요?",
    allHelpCards: "모든 도움 카드 →",
    emergency: "긴급",
    helpPage: "긴급 페이지 →",
    beforeYouAsk: "묻기 전에",
    allFaq: "자주 묻는 질문 →",
    tip1t: "현금이 마지막 수단",
    tip1b: "작은 가게에서는 해외 카드가 자주 거절됩니다. 200~500위안을 가지고 다니세요.",
    tip2t: "여권이 곧 승차권",
    tip2b: "기차, 호텔, 많은 결제에 필요합니다. 항상 들고 다니고 사진도 저장하세요.",
    tip3t: "먼저 호텔 프런트에 물어보세요",
    tip3b: "전화, 통역, 예약, 메모를 도와줍니다. 손님을 돕는 것이 그들의 일입니다.",
    footnote: "내용 최종 확인일: 2026-09-23. 정책, 결제, 발권 규칙은 바뀝니다. 공식 앱에서 확인하세요. 본 도구는 운영 절차만 제공하며 법률, 의료, 재무 조언이 아닙니다.",
    task: "한마디로",
    onThisPage: "이 페이지 목차",
    beforeYouStart: "시작 전 준비",
    tipLabel: "💡 팁",
    stepByStep: "단계별 진행",
    done: "완료",
    steps: "단계",
    showThisScreen: "이 화면을 보여주세요",
    openFullScreen: "전체 화면으로 열기 🗣️",
    usefulCards: "중국어 도움 카드",
    cards: "장",
    commonMistakes: "흔한 실수",
    colMistake: "실수",
    colWhy: "문제점",
    colDo: "이렇게 하세요",
    planB: "대안 — 안 될 때",
    trouble: "문제가 생기면",
    pleaseNote: "⚠️ 주의",
    officialSources: "공식 출처: ",
    outdated: "이 정보는 오래되었습니다",
    backToTasks: "전체 목록으로",
    show: "보여주기 ›",
    helpCards: "도움 카드",
    sets: "세트",
    howToUseCard: "카드 사용법",
    howToUseCardB: "카드를 누르면 전체 화면으로 열립니다. 중국어가 크게 표시되니 상대방에게 휴대폰을 그대로 건네세요. 영어가 방해되면 **Hide English** 를 누르세요.",
    howToUseCardC: "세트는 **긴급한 순서**로 정렬되어 있습니다. 어디를 봐야 할지 모르겠으면 맨 위부터 보세요.",
    faqTitle: "자주 묻는 질문",
    faqNote: "답변은 일반적인 경우입니다. 규칙은 바뀝니다 — 공식 앱에서 확인하세요.",
    showThisToThem: "상대방에게 보여주기",
    usefulCard: "도움 카드",
    hideEnglish: "영어 숨기기",
    showEnglish: "영어 보기",
    copyZh: "중국어 복사",
    copied: "복사됨 ✓",
    copyFailed: "복사 실패 — 직접 선택하세요",
    thanksLogged: "감사합니다 — 검토 목록에 기록했습니다",
    allStepsDone: "모든 단계 완료 🎉",
    matchingCards: "개의 카드",
    noMatch: "결과 없음. \"택시\", \"결제\", \"기차\" 등으로 검색해 보세요.",
    howToUse: "사용법",
    howToUseSub: "30초면 충분합니다",
    language: "언어",
    installApp: "앱 설치",
    installHint: "브라우저 메뉴에서 'ChinaPASS 설치'를 선택하면 홈 화면에 추가할 수 있습니다.",
    prepTitle: "출발 전 준비",
    prepSub: "탑승 전에 해두세요. 각 항목이 도착 후 겪을 문제를 하나씩 없애 줍니다.",
    prepDone: "완료",
    prepAllDone: "모두 준비됐습니다. 좋은 여행 되세요.",
    prepNoteTitle: "최신 요건 확인",
    prepNoteBody: "입국 규정, 결제 지원, 앱 제공 상황은 바뀝니다. 출발 전에 공식 출처에서 확인하세요.",
    prepNoteLink: "공식 여행 서비스 ↗",
    city: "도시",
    cityTitle: "어느 도시에 있나요?",
    cityHint: "현지 정보와 위치 카드를 만드는 데 사용합니다. 좌표는 휴대폰 밖으로 나가지 않습니다.",
    cityDetect: "현재 위치로 찾기",
    cityDetecting: "위치 확인 중…",
    cityPick: "또는 직접 선택",
    cityNone: "미설정",
    citySet: "현재 위치",
    showLocationCard: "📍 내 위치 카드 보여주기",
    locationNeedCity: "먼저 도시를 설정하세요",
    locationNeedsHttps: "위치 정보는 https 연결이 필요합니다. 도시를 선택하세요.",
    locationDenied: "위치 권한이 없습니다. 도시를 선택하세요.",
    aiTitle: "AI에게 묻기",
    aiBody: "\"지금 뭘 해야 하지?\"를 모국어로 답하는 챗. 아직 만들지 않았습니다.",
    aiCta: "준비 중",
    onboardNext: "다음",
    onboardStart: "시작",
    onboardSkip: "건너뛰기",
    partialNotice: "이 페이지는 아직 번역이 완료되지 않았습니다 — 일부는 영어로 표시됩니다.",
    partialShort: "일부 페이지 영어",
    back: "뒤로",
    close: "닫기",
    settings: "설정",
  },
};

/* ==========================================================================
   双语急救卡片库
   场景引用这里的 group id，卡片页展示全部。
   卡片形状：{ zh: <递给对方看的中文>, en/ja/ko: <释义> }
   ========================================================================== */

const CARD_GROUPS = {
  pay: {
    icon: "💳",
    title: { en: "Payment", zh: "支付", ja: "支払い", ko: "결제" },
    hint: { en: "At the counter or the till", zh: "在柜台 / 收银台", ja: "レジ・カウンターで", ko: "계산대에서" },
    cards: [
      { zh: "可以刷卡吗？", en: "Can I pay by card?", ja: "カードで払えますか？", ko: "카드로 결제할 수 있나요?" },
      { zh: "可以用支付宝吗？", en: "Can I pay by Alipay?", ja: "Alipayで払えますか？", ko: "알리페이로 결제할 수 있나요?" },
      { zh: "你们收外国银行卡吗？", en: "Do you accept foreign cards?", ja: "外国のカードは使えますか？", ko: "해외 카드도 받으시나요?" },
      { zh: "支付失败了。", en: "The payment failed.", ja: "支払いに失敗しました。", ko: "결제가 실패했습니다." },
      { zh: "请再试一次。", en: "Please try again.", ja: "もう一度お願いします。", ko: "다시 한 번 시도해 주세요." },
      { zh: "请给我一张小票。", en: "Please give me a receipt.", ja: "レシートをください。", ko: "영수증을 주세요." },
      { zh: "一共多少钱？", en: "How much is it in total?", ja: "全部でいくらですか？", ko: "총 얼마예요?" },
    ],
  },
  taxi: {
    icon: "🚕",
    title: { en: "Taxi", zh: "打车", ja: "タクシー", ko: "택시" },
    hint: { en: "Talking to your driver", zh: "和司机沟通", ja: "運転手とのやり取り", ko: "기사님과 대화" },
    cards: [
      { zh: "我在 B 出口。", en: "I am at Exit B.", ja: "B出口にいます。", ko: "B 출구에 있어요." },
      { zh: "我穿着黑色外套。", en: "I am wearing a black jacket.", ja: "黒い上着を着ています。", ko: "검은색 재킷을 입고 있어요." },
      { zh: "请等我 2 分钟。", en: "Please wait 2 minutes.", ja: "2分待ってください。", ko: "2분만 기다려 주세요." },
      { zh: "我不会说中文。", en: "I don't speak Chinese.", ja: "中国語が話せません。", ko: "중국어를 못합니다." },
      { zh: "请带我去这个地址。", en: "Please take me to this address.", ja: "この住所までお願いします。", ko: "이 주소로 가 주세요." },
      { zh: "请打表。", en: "Please use the meter.", ja: "メーターを使ってください。", ko: "미터기를 켜 주세요." },
      { zh: "请在这里停车。", en: "Please stop here.", ja: "ここで止めてください。", ko: "여기서 세워 주세요." },
      { zh: "多少钱？", en: "How much is it?", ja: "いくらですか？", ko: "얼마예요?" },
      { zh: "可以支付宝付款吗？", en: "Can I pay by Alipay?", ja: "Alipayで払えますか？", ko: "알리페이로 결제할 수 있나요?" },
    ],
  },
  train: {
    icon: "🚄",
    title: { en: "Train", zh: "高铁", ja: "高速鉄道", ko: "고속철도" },
    hint: { en: "Stations, seats and tickets", zh: "车站、座位和车票", ja: "駅・座席・切符", ko: "역, 좌석, 승차권" },
    cards: [
      { zh: "检票口在哪里？", en: "Where is the ticket gate?", ja: "改札口はどこですか？", ko: "개찰구가 어디예요?" },
      { zh: "在几号站台？", en: "Which platform is it?", ja: "何番ホームですか？", ko: "몇 번 승강장이에요?" },
      { zh: "这是我的座位。", en: "This is my seat.", ja: "これは私の席です。", ko: "제 자리입니다." },
      { zh: "这个座位有人吗？", en: "Is this seat taken?", ja: "この席は空いていますか？", ko: "이 자리 비었나요?" },
      { zh: "我需要改签。", en: "I need to change my ticket.", ja: "切符を変更したいです。", ko: "승차권을 변경하고 싶어요." },
      { zh: "候车室在哪里？", en: "Where is the waiting room?", ja: "待合室はどこですか？", ko: "대합실이 어디예요?" },
      { zh: "请帮帮我，我不会说中文。", en: "Please help me, I don't speak Chinese.", ja: "助けてください、中国語が話せません。", ko: "도와주세요, 중국어를 못합니다." },
    ],
  },
  metro: {
    icon: "🚇",
    title: { en: "Metro", zh: "地铁", ja: "地下鉄", ko: "지하철" },
    hint: { en: "Stations, lines and exits", zh: "车站、线路和出口", ja: "駅・路線・出口", ko: "역, 노선, 출구" },
    cards: [
      { zh: "地铁站在哪里？", en: "Where is the metro station?", ja: "地下鉄の駅はどこですか？", ko: "지하철역이 어디예요?" },
      { zh: "哪条线去机场？", en: "Which line goes to the airport?", ja: "空港へは何線ですか？", ko: "공항 가는 노선은 뭐예요?" },
      { zh: "是在这个站台吗？", en: "Is this the right platform?", ja: "このホームで合っていますか？", ko: "이 승강장이 맞아요?" },
      { zh: "我需要买票。", en: "I need to buy a ticket.", ja: "切符を買いたいです。", ko: "표를 사야 해요." },
      { zh: "我应该走哪个出口？", en: "Which exit should I take?", ja: "どの出口ですか？", ko: "어느 출구로 나가야 해요?" },
    ],
  },
  hotel: {
    icon: "🏨",
    title: { en: "Hotel", zh: "酒店", ja: "ホテル", ko: "호텔" },
    hint: { en: "Front desk, check-in, luggage", zh: "前台、入住、行李", ja: "フロント・チェックイン・荷物", ko: "프런트, 체크인, 짐" },
    cards: [
      { zh: "我用护照预订了房间。", en: "I have a reservation under my passport name.", ja: "パスポート名で予約しています。", ko: "여권 이름으로 예약했습니다." },
      { zh: "请帮我办理入住。", en: "Could you help me check in?", ja: "チェックインをお願いします。", ko: "체크인을 도와주세요." },
      { zh: "早餐几点？", en: "What time is breakfast?", ja: "朝食は何時ですか？", ko: "조식은 몇 시예요?" },
      { zh: "我需要付押金吗？", en: "Do I need to pay a deposit?", ja: "デポジットは必要ですか？", ko: "보증금을 내야 하나요?" },
      { zh: "可以帮我叫车吗？", en: "Can you help me call a taxi?", ja: "タクシーを呼んでもらえますか？", ko: "택시를 불러 주실 수 있나요?" },
      { zh: "可以帮我寄存行李吗？", en: "Could you keep my luggage?", ja: "荷物を預かってもらえますか？", ko: "짐을 맡아 주실 수 있나요?" },
      { zh: "可以延迟退房吗？", en: "Can I have a late check-out?", ja: "レイトチェックアウトはできますか？", ko: "늦게 체크아웃할 수 있나요?" },
      { zh: "可以帮我把地址写成中文吗？", en: "Could you write the address in Chinese for me?", ja: "住所を中国語で書いてもらえますか？", ko: "주소를 중국어로 적어 주실 수 있나요?" },
      { zh: "可以帮我点一份外卖吗？", en: "Could you help me order food?", ja: "出前を注文してもらえますか？", ko: "배달 음식을 주문해 주실 수 있나요?" },
    ],
  },
  food: {
    icon: "🍜",
    title: { en: "Food Delivery", zh: "外卖", ja: "デリバリー", ko: "배달 음식" },
    hint: { en: "Riders and dietary notes", zh: "骑手和忌口备注", ja: "配達員・リクエスト", ko: "배달원과 요청 사항" },
    cards: [
      { zh: "不要辣。", en: "No spicy.", ja: "辛くしないでください。", ko: "맵지 않게 해 주세요." },
      { zh: "不要花生。", en: "No peanuts.", ja: "ピーナッツ抜きで。", ko: "땅콩 빼주세요." },
      { zh: "不要香菜。", en: "No cilantro.", ja: "パクチー抜きで。", ko: "고수 빼주세요." },
      { zh: "请放在酒店前台。", en: "Please leave it at the hotel front desk.", ja: "ホテルのフロントに置いてください。", ko: "호텔 프런트에 놓아 주세요." },
      { zh: "到达时请打电话给我。", en: "Please call me when you arrive.", ja: "着いたら電話してください。", ko: "도착하면 전화해 주세요." },
      { zh: "我不会说中文。", en: "I don't speak Chinese.", ja: "中国語が話せません。", ko: "중국어를 못합니다." },
      { zh: "我的房间号是 ___。", en: "My room number is ___.", ja: "部屋番号は ___ です。", ko: "제 객실 번호는 ___ 입니다." },
      { zh: "订单送错了。", en: "The order is wrong.", ja: "注文が違います。", ko: "주문이 잘못 왔어요." },
    ],
  },
  sim: {
    icon: "📶",
    title: { en: "SIM / Internet", zh: "电话卡", ja: "SIM・通信", ko: "SIM / 인터넷" },
    hint: { en: "Buying a SIM or topping up", zh: "买卡或充值", ja: "SIM購入・チャージ", ko: "SIM 구매와 충전" },
    cards: [
      { zh: "我想买一张电话卡。", en: "I want to buy a SIM card.", ja: "SIMカードを買いたいです。", ko: "SIM 카드를 사고 싶어요." },
      { zh: "每个月多少钱？", en: "How much is it per month?", ja: "月いくらですか？", ko: "한 달에 얼마예요?" },
      { zh: "我的手机能用吗？", en: "Does it work with my phone?", ja: "私のスマホで使えますか？", ko: "제 휴대폰에서 쓸 수 있나요?" },
      { zh: "我需要一个能收短信的号码。", en: "I need a number that can receive SMS.", ja: "SMSが受け取れる番号が必要です。", ko: "문자를 받을 수 있는 번호가 필요해요." },
      { zh: "可以帮我设置一下吗？", en: "Could you help me set it up?", ja: "設定を手伝ってもらえますか？", ko: "설정을 도와주실 수 있나요?" },
    ],
  },
  hospital: {
    icon: "🏥",
    title: { en: "Hospital", zh: "医院", ja: "病院", ko: "병원" },
    hint: { en: "When you feel unwell", zh: "身体不舒服时", ja: "体調が悪いとき", ko: "몸이 안 좋을 때" },
    cards: [
      { zh: "我身体不舒服。", en: "I don't feel well.", ja: "体調が悪いです。", ko: "몸이 안 좋아요." },
      { zh: "我需要看医生。", en: "I need to see a doctor.", ja: "医者に診てもらいたいです。", ko: "의사를 만나야 해요." },
      { zh: "我发烧了。", en: "I have a fever.", ja: "熱があります。", ko: "열이 있어요." },
      { zh: "我肚子疼。", en: "I have a stomachache.", ja: "お腹が痛いです。", ko: "배가 아파요." },
      { zh: "我对 ___ 过敏。", en: "I am allergic to ___.", ja: "___ にアレルギーがあります。", ko: "___ 에 알레르기가 있어요." },
      { zh: "我在吃这个药。", en: "I am taking this medicine.", ja: "この薬を飲んでいます。", ko: "이 약을 먹고 있어요." },
      { zh: "我的护照号码是 ___。", en: "My passport number is ___.", ja: "パスポート番号は ___ です。", ko: "여권 번호는 ___ 입니다." },
      { zh: "药店在哪里？", en: "Where is the pharmacy?", ja: "薬局はどこですか？", ko: "약국이 어디예요?" },
    ],
    /* compliance line — rendered on the /cards index next to this group.
       docs/09: medical content describes the flow for getting care, it never
       offers a diagnosis or a treatment suggestion. */
    note: {
      en: "These cards are for communication only. They are not medical advice.",
      zh: "这些卡片只用于沟通，不构成医疗建议。",
      ja: "これらのカードは意思疎通のためのもので、医学的助言ではありません。",
      ko: "이 카드들은 의사소통용이며 의학적 조언이 아닙니다.",
    },
  },
  lost: {
    icon: "🎒",
    title: { en: "Lost & Found", zh: "丢失物品", ja: "紛失・忘れ物", ko: "분실물" },
    hint: { en: "Passport, phone or bag missing", zh: "护照、手机或包丢了", ja: "パスポート・スマホ・荷物", ko: "여권, 휴대폰, 가방 분실" },
    cards: [
      { zh: "我的手机丢了。", en: "I lost my phone.", ja: "スマホをなくしました。", ko: "휴대폰을 잃어버렸어요." },
      { zh: "我的护照丢了。", en: "I lost my passport.", ja: "パスポートをなくしました。", ko: "여권을 잃어버렸어요." },
      { zh: "我的包落在出租车上了。", en: "I left my bag in the taxi.", ja: "タクシーに荷物を忘れました。", ko: "택시에 가방을 두고 내렸어요." },
      { zh: "可以帮我报警吗？", en: "Can you help me call the police?", ja: "警察を呼んでもらえますか？", ko: "경찰을 불러 주실 수 있나요?" },
      { zh: "最近的警察局在哪里？", en: "Where is the nearest police station?", ja: "一番近い警察署はどこですか？", ko: "가장 가까운 경찰서가 어디예요?" },
      { zh: "我需要一份报警记录用于保险。", en: "I need a police report for my insurance.", ja: "保険用に警察の証明が必要です。", ko: "보험을 위해 경찰 신고 기록이 필요해요." },
    ],
  },
  phone: {
    icon: "🔋",
    title: { en: "Phone Battery Dead", zh: "手机没电", ja: "スマホの充電切れ", ko: "휴대폰 배터리 방전" },
    hint: { en: "When your phone is about to die", zh: "手机快没电时", ja: "充電が切れそうなとき", ko: "배터리가 얼마 없을 때" },
    cards: [
      { zh: "我的手机快没电了。", en: "My phone is about to die.", ja: "スマホの充電が切れそうです。", ko: "휴대폰 배터리가 거의 없어요." },
      { zh: "我可以在这里充电吗？", en: "Could I charge my phone here?", ja: "ここで充電できますか？", ko: "여기서 충전할 수 있나요?" },
      { zh: "请帮我联系我的朋友。", en: "Please help me contact my friend.", ja: "友達に連絡してもらえますか？", ko: "친구에게 연락을 도와주세요." },
      { zh: "他/她的电话是 ___。", en: "His/Her phone number is ___.", ja: "電話番号は ___ です。", ko: "전화번호는 ___ 입니다." },
      { zh: "非常感谢！", en: "Thank you very much!", ja: "本当にありがとうございます！", ko: "정말 감사합니다!" },
    ],
  },
  toilet: {
    icon: "🚻",
    title: { en: "Toilet & Basics", zh: "厕所 / 日常", ja: "トイレ・基本", ko: "화장실 / 기본" },
    hint: { en: "Toilet, tissues, elevator", zh: "厕所、纸巾、电梯", ja: "トイレ・ティッシュ・エレベーター", ko: "화장실, 휴지, 엘리베이터" },
    cards: [
      { zh: "请问洗手间在哪里？", en: "Where is the toilet?", ja: "トイレはどこですか？", ko: "화장실이 어디예요?" },
      { zh: "洗手间怎么走？", en: "How do I get to the toilet?", ja: "トイレへはどう行きますか？", ko: "화장실에 어떻게 가요?" },
      { zh: "请问有纸巾吗？", en: "Do you have tissues?", ja: "ティッシュはありますか？", ko: "휴지 있어요?" },
      { zh: "请问有电梯吗？", en: "Is there an elevator?", ja: "エレベーターはありますか？", ko: "엘리베이터 있어요?" },
      { zh: "最近的便利店在哪里？", en: "Where is the nearest convenience store?", ja: "一番近いコンビニはどこですか？", ko: "가장 가까운 편의점이 어디예요?" },
      { zh: "我可以借一下洗手间吗？", en: "May I use your toilet?", ja: "トイレを借りてもいいですか？", ko: "화장실 좀 써도 될까요?" },
    ],
  },
  directions: {
    icon: "🧭",
    title: { en: "Directions", zh: "找路", ja: "道案内", ko: "길 찾기" },
    hint: { en: "When you can't find the place", zh: "找不到地方时", ja: "場所が見つからないとき", ko: "장소를 못 찾을 때" },
    cards: [
      { zh: "我迷路了。", en: "I am lost.", ja: "道に迷いました。", ko: "길을 잃었어요." },
      { zh: "请问怎么去这个地方？", en: "How do I get to this place?", ja: "ここへはどう行きますか？", ko: "여기는 어떻게 가요?" },
      { zh: "离这里远吗？", en: "Is it far from here?", ja: "ここから遠いですか？", ko: "여기서 멀어요?" },
      { zh: "我应该坐几号线？", en: "Which metro line should I take?", ja: "何号線に乗ればいいですか？", ko: "몇 호선을 타야 해요?" },
      { zh: "入口在哪里？", en: "Where is the entrance?", ja: "入口はどこですか？", ko: "입구가 어디예요?" },
      { zh: "可以在地图上指给我看吗？", en: "Could you show me on the map?", ja: "地図で示してもらえますか？", ko: "지도에서 알려 주실 수 있나요?" },
    ],
  },
  emergency: {
    icon: "🆘",
    title: { en: "Emergency", zh: "报警 / 求助", ja: "緊急・通報", ko: "긴급 / 신고" },
    hint: { en: "When it's urgent — police, ambulance, fire", zh: "紧急时 —— 报警、救护、火警", ja: "緊急時 — 警察・救急・消防", ko: "긴급할 때 — 경찰, 구급, 소방" },
    cards: [
      { zh: "我需要帮助。", en: "I need help.", ja: "助けが必要です。", ko: "도움이 필요해요." },
      { zh: "请报警。", en: "Please call the police.", ja: "警察を呼んでください。", ko: "경찰에 신고해 주세요." },
      { zh: "请叫救护车。", en: "Please call an ambulance.", ja: "救急車を呼んでください。", ko: "구급차를 불러 주세요." },
      { zh: "这里有紧急情况。", en: "There is an emergency.", ja: "緊急事態です。", ko: "긴급 상황입니다." },
      { zh: "我不会说中文。", en: "I don't speak Chinese.", ja: "中国語が話せません。", ko: "중국어를 못합니다." },
      { zh: "请帮我找一个翻译。", en: "Please help me find an interpreter.", ja: "通訳を探してもらえますか？", ko: "통역사를 찾아 주실 수 있나요?" },
      { zh: "请带我去最近的医院。", en: "Please take me to the nearest hospital.", ja: "一番近い病院へ連れて行ってください。", ko: "가장 가까운 병원으로 데려가 주세요." },
    ],
  },
};

/* ==========================================================================
   海关 / 入境 —— 落地第一件事
   政策类内容：只写操作步骤，不做法律判断，不承诺一定能入境。
   ========================================================================== */

CARD_GROUPS.customs = {
  icon: "🛃",
  title: { en: "Customs & Entry", zh: "海关 / 入境", ja: "税関・入国", ko: "세관 / 입국" },
  hint: { en: "Immigration, baggage, customs", zh: "边检、行李、海关", ja: "入国審査・荷物・税関", ko: "입국 심사, 수하물, 세관" },
  cards: [
    { zh: "我是外国旅客，来旅游。", en: "I am a foreign tourist.", ja: "外国人観光客です。", ko: "외국인 관광객입니다." },
    { zh: "我会在这里停留 ___ 天。", en: "I will stay for ___ days.", ja: "___ 日間滞在します。", ko: "___ 일 동안 머뭅니다." },
    { zh: "我住在这家酒店。", en: "I am staying at this hotel.", ja: "このホテルに泊まります。", ko: "이 호텔에 묵습니다." },
    { zh: "我不会说中文，请帮我找翻译。", en: "I don't speak Chinese. Please find an interpreter.", ja: "中国語が話せません。通訳をお願いします。", ko: "중국어를 못합니다. 통역을 부탁드립니다." },
    { zh: "请问入境卡怎么填？", en: "How do I fill in the arrival card?", ja: "入国カードの書き方を教えてください。", ko: "입국 카드는 어떻게 작성하나요?" },
    { zh: "请问取行李的地方在哪里？", en: "Where is the baggage claim?", ja: "手荷物受取所はどこですか？", ko: "수하물 찾는 곳이 어디예요?" },
    { zh: "我的行李没有到。", en: "My luggage did not arrive.", ja: "荷物が届いていません。", ko: "제 짐이 도착하지 않았어요." },
    { zh: "这个需要申报吗？", en: "Do I need to declare this?", ja: "これは申告が必要ですか？", ko: "이것을 신고해야 하나요?" },
  ],
};

/* ==========================================================================
   展示顺序
   显式写出来，不依赖对象键 / 数组的隐式顺序。改顺序只改这些数组。
   ========================================================================== */

/* 卡片组：按紧急程度从高到低 */
const CARD_ORDER = [
  "emergency",   // 最急：报警、救护车
  "hospital",    // 身体不舒服
  "lost",        // 护照 / 手机 / 包丢了
  "phone",       // 手机没电
  "customs",     // 落地过关
  "directions",  // 迷路
  "toilet",      // 高频：厕所、纸巾
  "taxi",        // 高频：联系司机
  "hotel",       // 高频：前台沟通
  "food",        // 高频：外卖忌口
  "pay",         // 日常
  "metro",       // 日常
  "train",       // 日常
  "sim",         // 日常
];

/* 场景：按「一次真实落地」的时间线排列 */
const SCENE_ORDER = [
  "customs",     // 下飞机 → 出机场
  "sim",         // 先有网
  "pay",         // 才能设支付
  "taxi",        // 才走得了
  "hotel",       // 落脚
  "metro",       // 日常出行
  "train",       // 跨城
  "food",        // 吃饭
  "emergency",   // 兜底
];

/* ==========================================================================
   场景
   ========================================================================== */

const SCENES = [
  {
    id: "customs",
    icon: "🛃",
    title: { en: "Customs & Entry", zh: "海关 / 入境", ja: "税関・入国", ko: "세관 / 입국" },
    subtitle: { en: "From the plane to the exit", zh: "从下飞机到出机场", ja: "飛行機を降りて出口まで", ko: "비행기에서 공항 출구까지" },
    category: { en: "Arrival", zh: "落地", ja: "到着", ko: "입국" },
    priority: "P0",
    eta: { en: "30–60 min", zh: "30–60 分钟", ja: "30〜60分", ko: "30~60분" },
    lastUpdated: "2026-09-23",
    task: "Get through immigration and customs after you land, and reach the exit hall.",
    before: [
      "Your passport",
      "Your visa, or proof you qualify for visa-free entry",
      "The arrival card, if the crew handed you one on the plane",
      "A pen — the desks often run out",
      "Your hotel address written in Chinese",
    ],
    tip: "Fill in the arrival card before you reach the queue. Have your passport, the card and your hotel address in your hand — not in your bag.",
    steps: [
      { t: "Follow the Arrivals signs", d: "Do not follow Transfer (中转) unless you are changing flights. Arrivals is usually 到达 or 国际到达." },
      { t: "Fill in the arrival card", d: "Write in block capitals. Use the hotel address in Chinese. Ask a crew member if a field is unclear." },
      { t: "Join the foreign passport queue", d: "The lane is marked 外国人 / Foreigners. The Chinese nationals lane will send you back." },
      { t: "Answer the officer's questions", d: "Purpose of visit, how many days, where you are staying. Answer briefly. Keep the stamped slip they return to you." },
      { t: "Collect your baggage", d: "Check the screens for your flight number and carousel. Trolleys are free." },
      { t: "Choose a customs channel", d: "Green (无申报) if you have nothing to declare. Red (申报) if you are carrying goods over the allowance." },
      { t: "Exit to the arrivals hall", d: "You will pass money changers, SIM counters and taxi stands. Set up your phone before you leave the building." },
    ],
    mistakes: [
      { m: "Joining the wrong queue", w: "You will be sent to the back of the foreigner lane", d: "Look for 外国人 / Foreigners" },
      { m: "Losing the stamped slip", w: "You may need it when you check in or leave", d: "Keep it with your passport" },
      { m: "Writing the hotel address in English only", w: "Nobody can read it if you are asked", d: "Have the Chinese address ready" },
      { m: "Leaving your phone off", w: "You cannot book a taxi or reach your hotel", d: "Get a SIM or eSIM working at the airport" },
    ],
    cardGroups: ["customs", "directions", "toilet"],
    showCard: {
      title: "Show this at the airport",
      lines: ["你好，我是外国旅客，我不太会说中文。", "请问取行李的地方在哪里？", "我住在这个酒店，地址是：[中文地址]", "谢谢！"],
    },
    planB: [
      "Ask at the information desk (问询处). Staff at airport desks usually handle basic English.",
      "Show your passport and booking confirmation to any uniformed staff member.",
      "Use your phone's translation app on the officer's question, and show the screen.",
      "If a form confuses you, ask the crew before landing — they have more time then.",
    ],
    trouble: [
      { p: "The officer asks something you don't understand", a: "Say \"I don't speak Chinese\", then show the customs card. Point at your passport and booking." },
      { p: "You lost or never got the arrival card", a: "Ask staff near the queue. Spare cards are usually on a shelf or desk there." },
      { p: "Your bag did not arrive", a: "Go to the airline's Lost & Found desk before you leave the hall. File a report and keep the copy." },
      { p: "You have goods to declare and are unsure", a: "Take the red channel and ask the officer. Declaring is always safer than not declaring." },
    ],
    sources: [
      { label: "National Immigration Administration", url: "https://www.nia.gov.cn/" },
      { label: "General Administration of Customs", url: "http://www.customs.gov.cn/" },
    ],
    disclaimer: "Entry rules depend on your nationality, visa and current policy. This page describes the airport steps only. It is not legal or visa advice, and it cannot promise any outcome at the border.",
  },

  {
    id: "pay",
    icon: "💳",
    title: { en: "Pay", zh: "支付", ja: "支払い", ko: "결제" },
    subtitle: { en: "How to pay with Alipay", zh: "怎么用支付宝付款", ja: "Alipayでの支払い方", ko: "알리페이 결제 방법" },
    category: { en: "Money", zh: "钱", ja: "お金", ko: "결제" },
    priority: "P0",
    eta: { en: "3 min", zh: "3 分钟", ja: "3分", ko: "3분" },
    lastUpdated: "2026-09-23",
    task: "Set up Alipay with your own bank card, then pay in a shop or online.",
    before: [
      "Phone with internet (eSIM or local SIM)",
      "Your passport",
      "A card in your own name (Visa / Mastercard / JCB / Discover)",
      "A phone number that can receive SMS",
    ],
    steps: [
      { t: "Download Alipay", d: "Install it from the App Store or Google Play. The publisher is Ant Group." },
      { t: "Sign up with your own phone number", d: "International numbers work. You will need this number again for verification." },
      { t: "Verify your identity", d: "Tap Me → Account → Identity Verification. Photograph your passport. Payment stays locked until this is approved." },
      { t: "Add a bank card", d: "Tap Me → Bank Cards → Add Bank Card. Enter the card number, expiry date and CVC." },
      { t: "Confirm with your bank", d: "Your bank sends a one-time code by SMS. Enter it in the app." },
      { t: "Pay in a shop", d: "Two ways: scan the shop's QR code, or show your payment code (Me → Pay) to the cashier's scanner." },
      { t: "Check your limits", d: "Me → Bank Cards shows the limit for each card. Foreign cards have lower limits than Chinese cards." },
      { t: "If a payment fails", d: "Try the other payment method first. If it still fails, use Plan B below." },
    ],
    mistakes: [
      { m: "Using someone else's card", w: "The card name must match your verified identity", d: "Use a card in your own name" },
      { m: "Skipping passport verification", w: "Payments fail and features stay locked", d: "Finish verification before you travel" },
      { m: "Assuming every shop takes foreign cards", w: "Small vendors use personal QR transfers", d: "Carry some cash as a backup" },
      { m: "Paying before checking the amount", w: "You may overpay, and refunds take days", d: "Check the amount on the screen first" },
    ],
    cardGroups: ["pay"],
    showCard: {
      title: "Show this to the cashier",
      lines: ["你好，我想用支付宝付款。", "请扫这个付款码。", "如果不行，我可以付现金。", "谢谢！"],
    },
    planB: [
      "Pay in cash. Yuan (CNY) works everywhere. Withdraw at an ATM with your Visa / Mastercard / UnionPay logo.",
      "Ask the hotel to pay for you, and add it to your room bill.",
      "Ask a friend to pay, and send them the money later.",
      "Try WeChat Pay. It also supports foreign cards — if one app rejects your card, try the other.",
    ],
    trouble: [
      { p: "Payment declined", a: "Check the card limit in Me → Bank Cards, then try a smaller amount." },
      { p: "Card will not add", a: "Contact your bank. Many banks block China transactions by default." },
      { p: "Refund not received", a: "Refunds go back to the original card. This can take several working days." },
      { p: "Charged twice", a: "Open the order → Feedback and report it. Keep the receipt." },
    ],
    sources: [
      { label: "Alipay official site", url: "https://www.alipay.com/" },
    ],
    disclaimer: "Limits and card support change often. Check the current limit inside the app before you rely on it.",
  },

  {
    id: "taxi",
    icon: "🚕",
    title: { en: "Taxi", zh: "打车", ja: "タクシー", ko: "택시" },
    subtitle: { en: "How to take a taxi (DiDi)", zh: "怎么用滴滴打车", ja: "DiDiでの配車", ko: "디디로 택시 부르기" },
    category: { en: "Transport", zh: "交通", ja: "移動", ko: "교통" },
    priority: "P0",
    eta: { en: "3 min", zh: "3 分钟", ja: "3分", ko: "3분" },
    lastUpdated: "2026-09-16",
    task: "Take a taxi with DiDi, from opening the app to arriving at your hotel.",
    before: [
      "Phone with internet (eSIM or local SIM)",
      "DiDi app installed, or Alipay → Transport / Ride mini-app",
      "Your destination written in Chinese (copy it from your booking)",
      "Alipay or WeChat Pay linked to a card",
    ],
    tip: "Before you leave your hotel, ask the front desk to write the hotel name and address in Chinese. Save it in your notes. You will need it every time you come back.",
    steps: [
      { t: "Open DiDi", d: "Or open Alipay → Transport → Ride." },
      { t: "Switch to English", d: "Tap the profile icon → Settings → Language → English." },
      { t: "Enter your destination", d: "Paste the Chinese address. Do not type only \"Hilton Hotel\" in English — it may match the wrong city." },
      { t: "Check the pickup point", d: "The app shows a green pin. Walk to it. If it is on the wrong side of the road, drag the map to adjust." },
      { t: "Choose a ride type", d: "\"Express\" (快车) is the cheapest standard option. \"Premier\" costs more." },
      { t: "Tap Confirm and wait", d: "The app shows the driver's plate number and car model." },
      { t: "Check the plate number before you get in", d: "Match the last 3–4 characters on the plate." },
      { t: "Pay in the app", d: "Do not pay cash unless the driver asks. The fare is charged automatically after arrival." },
    ],
    mistakes: [
      { m: "Typing only the hotel name in English", w: "The driver may go to the wrong place, or cancel", d: "Paste the Chinese address" },
      { m: "Standing at the wrong exit", w: "The driver cannot find you, and you pay a waiting fee", d: "Check the pickup pin and the exit letter (A/B/C/D)" },
      { m: "Not checking the plate number", w: "You may get into the wrong car", d: "Match the plate before entering" },
      { m: "Canceling after the driver arrives", w: "A cancellation fee applies", d: "Cancel early, or message the driver first" },
      { m: "Not being able to describe yourself", w: "The driver gives up and cancels", d: "Use the bilingual card below" },
    ],
    cardGroups: ["taxi"],
    showCard: {
      title: "Show this to the driver",
      lines: ["你好，我不太会说中文。", "我在 B 出口，穿黑色外套，请到这里接我。", "目的地是：[中文地址]", "谢谢！"],
    },
    planB: [
      "Ask the hotel front desk to call a taxi for you.",
      "Use the metro instead. Most cities have English signage and English ticket machines.",
      "Walk to a main road and hail a taxi. Show the Chinese address through the window first.",
      "Ask staff at a convenience store or mall information desk to order for you.",
    ],
    trouble: [
      { p: "Driver calls but you cannot understand", a: "Say \"Hello, I don't speak Chinese\" and send a text in the app instead." },
      { p: "You left something in the car", a: "Open the order in DiDi → Contact driver → Lost item." },
      { p: "You were charged too much", a: "Open the order → Feedback and report the fare." },
      { p: "Driver canceled", a: "Just re-order. No action needed." },
    ],
    sources: [],
  },

  {
    id: "train",
    icon: "🚄",
    title: { en: "Train", zh: "高铁", ja: "高速鉄道", ko: "고속철도" },
    subtitle: { en: "How to buy a high-speed rail ticket", zh: "怎么买高铁票", ja: "高速鉄道の切符の買い方", ko: "고속철도 표 사는 법" },
    category: { en: "Transport", zh: "交通", ja: "移動", ko: "교통" },
    priority: "P0",
    eta: { en: "5 min", zh: "5 分钟", ja: "5分", ko: "5분" },
    lastUpdated: "2026-09-23",
    task: "Buy a high-speed train ticket with your passport, and board the train.",
    before: [
      "Your passport (the number and spelling must be exact)",
      "12306 app, or Trip.com if you prefer a full English flow",
      "Alipay / WeChat Pay, or an international card",
      "Enough time: arrive at the station 45–60 minutes early",
    ],
    tip: "Big cities have several stations. Shanghai has Hongqiao, Shanghai Station and Shanghai South. Check the station name, not just the city.",
    steps: [
      { t: "Download the official app", d: "12306 is the official railway app and has an English version. Trip.com sells the same tickets in English for a small fee." },
      { t: "Register with your passport", d: "Enter your name exactly as printed on the passport. Spelling and word order must match." },
      { t: "Add yourself as a passenger", d: "In 12306, add a passenger with your passport number. You cannot buy a ticket until this is saved." },
      { t: "Search for trains", d: "Choose From and To, then the date. Use the English station names." },
      { t: "Pick the train type", d: "G = fastest. D = fast. C = intercity. Z / T / K = slower, often overnight." },
      { t: "Choose a seat class", d: "Second Class is standard. First Class has wider seats. Business Class is the most expensive." },
      { t: "Understand 候补 (Waitlist)", d: "Waitlist means you pay first. If another passenger cancels, the system may get a ticket for you automatically. If it fails, you are refunded." },
      { t: "Pay", d: "Alipay, WeChat Pay or an international card." },
      { t: "Board the train", d: "Your passport is your ticket. Use the staffed lane, not the automatic gate, and show your passport." },
      { t: "Change or refund", d: "You can change or refund in the app before departure. Fees depend on how close to departure you are." },
    ],
    mistakes: [
      { m: "Name does not match the passport", w: "The ticket cannot be used at the gate", d: "Copy the passport spelling exactly" },
      { m: "Arriving late", w: "Gates close about 5 minutes before departure", d: "Be at the station 45–60 minutes early" },
      { m: "Going to the wrong station", w: "You miss the train", d: "Check the station name on the ticket" },
      { m: "Using the automatic gate", w: "Foreign passports often fail to scan", d: "Use the staffed lane and show your passport" },
      { m: "Buying from a reseller on the street", w: "Overpriced, and the ticket may be invalid", d: "Use 12306 or a licensed agent" },
    ],
    cardGroups: ["train"],
    showCard: {
      title: "Show this at the station",
      lines: ["你好，我不会说中文。", "我要坐这班车，这是我的护照。", "请问检票口在哪里？", "谢谢！"],
    },
    planB: [
      "Buy through Trip.com or a travel agent that works in English.",
      "Fly instead. Check domestic flights for long distances.",
      "Take a slower overnight train, or a long-distance bus.",
      "Ask your hotel front desk to book it. Show them: 请帮我在 12306 上买一张到北京的高铁票。",
    ],
    trouble: [
      { p: "Ticket not showing in the app", a: "Open 12306 → Your Orders and screenshot it. Show the screenshot at the staffed lane." },
      { p: "Cannot pass the gate", a: "Go to the staffed lane and show your passport." },
      { p: "You missed the train", a: "Change to a later train on the same day in the app, as soon as possible." },
      { p: "You lost your passport", a: "Report it to the police, then go to your embassy." },
    ],
    sources: [
      { label: "12306 official site", url: "https://www.12306.cn/en/index.html" },
    ],
    disclaimer: "Ticket rules and change fees follow railway policy. Check the app for the current rules.",
  },

  {
    id: "metro",
    icon: "🚇",
    title: { en: "Metro", zh: "地铁", ja: "地下鉄", ko: "지하철" },
    subtitle: { en: "How to ride the metro", zh: "怎么坐地铁", ja: "地下鉄の乗り方", ko: "지하철 타는 법" },
    category: { en: "Transport", zh: "交通", ja: "移動", ko: "교통" },
    priority: "P1",
    eta: { en: "2 min", zh: "2 分钟", ja: "2分", ko: "2분" },
    lastUpdated: "2026-09-23",
    task: "Ride the metro from the street entrance to your stop.",
    before: [
      "Phone with internet",
      "Alipay or WeChat Pay, or small notes for a ticket machine",
      "Your destination station written in Chinese",
    ],
    steps: [
      { t: "Find the station", d: "Look for the metro logo. Entrances are marked with letters (A, B, C, D)." },
      { t: "Choose how to pay", d: "Buy a single ticket from a machine (English option available), or use Alipay → Transport → Metro." },
      { t: "Open your ride QR code", d: "Alipay → Transport → pick your city → Metro. Show the code at the gate." },
      { t: "Find your direction", d: "The platform sign shows the last station on the line. Match it to your line." },
      { t: "Check the route", d: "Amap (高德) and Baidu Maps show metro routes in English. Metro apps differ by city." },
      { t: "Watch your stop", d: "Announcements are in Chinese, then English in most big cities. Count the stops too." },
      { t: "Exit the right way", d: "Signs show exits A/B/C/D and the streets nearby. Check before you go up." },
      { t: "Tap out", d: "Scan the QR code again at the exit gate. You are charged by distance." },
    ],
    mistakes: [
      { m: "Standing on the wrong platform", w: "You travel away from your stop", d: "Match the last station on the sign to your direction" },
      { m: "Losing the single ticket", w: "You cannot leave the station", d: "Keep it until you tap out" },
      { m: "Traveling at rush hour with luggage", w: "Trains are packed at 07:30–09:30 and 17:30–19:30", d: "Travel outside those windows" },
      { m: "Not checking the exit letter", w: "You surface blocks from where you wanted", d: "Check the exit letter on the map first" },
    ],
    cardGroups: ["metro", "directions", "toilet"],
    planB: [
      "Take a taxi or DiDi instead.",
      "Take a bus. Pay with the same Alipay transport QR code.",
      "Show the station name to station staff and ask for help.",
      "Walk if it is under 20 minutes. Streets are busier but you can see landmarks.",
    ],
    trouble: [
      { p: "Gate will not open", a: "Show the QR code again, or go to the service window." },
      { p: "You went the wrong way", a: "Get off at the next station and take a train back." },
      { p: "Machine will not take your note", a: "Most accept 5 and 10 yuan notes, and some take coins." },
    ],
    sources: [],
  },

  {
    id: "hotel",
    icon: "🏨",
    title: { en: "Hotel", zh: "酒店", ja: "ホテル", ko: "호텔" },
    subtitle: { en: "How to check in", zh: "怎么办理入住", ja: "チェックインの仕方", ko: "체크인 하는 법" },
    category: { en: "Stay", zh: "住宿", ja: "宿泊", ko: "숙박" },
    priority: "P1",
    eta: { en: "3 min", zh: "3 分钟", ja: "3分", ko: "3분" },
    lastUpdated: "2026-09-23",
    task: "Check in to a hotel with your passport, and ask the front desk for what you need.",
    before: [
      "Your passport (every guest must show one)",
      "Booking confirmation",
      "A payment method for the deposit",
    ],
    steps: [
      { t: "Book a hotel that accepts foreign guests", d: "Not every hotel is licensed to register foreign passports. Use the \"accepts foreign guests\" filter, or call ahead." },
      { t: "Bring your passport to the desk", d: "The hotel registers your passport with the local police. This is normal and required." },
      { t: "Check in", d: "Hand over your passport and the booking name." },
      { t: "Confirm the details", d: "Ask about breakfast, deposit, check-out time and the Wi-Fi password." },
      { t: "Pay the deposit", d: "Usually a few hundred yuan. It is refunded at check-out." },
      { t: "Ask for the address in Chinese", d: "Save it in your phone. You need it for taxis and food delivery." },
      { t: "Ask the desk for help", d: "They can call a taxi, translate, write notes or order food for you." },
      { t: "Check out", d: "Return the key card. The deposit goes back to the original payment method." },
    ],
    mistakes: [
      { m: "Booking a hotel that cannot register foreign passports", w: "You are turned away at the desk", d: "Check before you book, or call the hotel" },
      { m: "Leaving your passport in the room safe", w: "You need it for trains, hotels and some payments", d: "Carry it with you" },
      { m: "Losing the deposit receipt", w: "Disputes are harder to resolve", d: "Keep the receipt and the payment record" },
      { m: "Assuming the desk speaks English", w: "Check-in takes much longer", d: "Use the bilingual cards below" },
    ],
    cardGroups: ["hotel", "toilet"],
    showCard: {
      title: "Show this at the front desk",
      lines: ["你好，我用护照预订了房间。", "请帮我办理入住。", "可以帮我把酒店地址写成中文吗？", "谢谢！"],
    },
    planB: [
      "If a guesthouse cannot register you, move to a larger hotel with a 24-hour front desk.",
      "Ask your booking platform's customer service to help you move.",
      "Ask the hotel to recommend a nearby hotel that accepts foreign guests.",
    ],
    trouble: [
      { p: "Hotel refuses your passport", a: "Ask them to help you find a hotel that can register foreign guests." },
      { p: "Deposit not returned", a: "Show your receipt and the original payment record." },
      { p: "You need to stay longer", a: "Ask at the front desk as early as possible. Rooms sell out." },
    ],
    sources: [
      { label: "National Immigration Administration", url: "https://www.nia.gov.cn/" },
    ],
    disclaimer: "Rules on registering foreign guests vary by city and by hotel. This page describes the usual steps only — it is not legal advice.",
  },

  {
    id: "food",
    icon: "🍜",
    title: { en: "Food", zh: "外卖", ja: "フードデリバリー", ko: "배달 음식" },
    subtitle: { en: "How to order delivery", zh: "怎么点外卖", ja: "デリバリーの注文", ko: "배달 주문하는 법" },
    category: { en: "Daily", zh: "日常", ja: "毎日", ko: "일상" },
    priority: "P1",
    eta: { en: "4 min", zh: "4 分钟", ja: "4分", ko: "4분" },
    lastUpdated: "2026-09-23",
    task: "Order food delivery to your hotel, and handle problems with the order.",
    before: [
      "Alipay or WeChat Pay linked to a card",
      "Your hotel address and room number",
      "Any allergy or dietary notes ready in Chinese",
    ],
    steps: [
      { t: "Open a delivery app", d: "Meituan (美团) and Ele.me (饿了么) are the two main apps. For English, use the food mini-app inside Alipay." },
      { t: "Set your address", d: "Type the hotel name in Chinese and add your room number. Save it as the default." },
      { t: "Pick a restaurant", d: "Check the rating, the delivery time and the minimum order." },
      { t: "Choose your food", d: "Add items to the cart, then tap Checkout." },
      { t: "Write a note for the kitchen", d: "Tap 备注 (Notes) and add your dietary needs. Use the cards below." },
      { t: "Pay in the app", d: "Never pay the rider in cash." },
      { t: "Watch the delivery", d: "The app shows the rider's position and an arrival time." },
      { t: "Meet the rider", d: "Most riders call when they arrive. Meet them in the lobby or at the delivery table." },
      { t: "If something is wrong", d: "Open the order → Contact rider or Customer service. Photograph the wrong item." },
    ],
    mistakes: [
      { m: "Writing the address only in English", w: "The rider cannot find the hotel", d: "Use the Chinese hotel name plus the room number" },
      { m: "Forgetting the room number", w: "The rider waits in the lobby", d: "Add the room number in the address" },
      { m: "Not checking the Notes field for allergens", w: "The kitchen does not know your allergy", d: "Write it in the Notes every time" },
      { m: "Not answering the rider's call", w: "The order is left outside, or canceled", d: "Answer, or send a text in the app" },
      { m: "Ordering at peak meal times", w: "Delivery takes much longer at 12:00–13:00 and 18:00–19:30", d: "Order 30 minutes earlier" },
    ],
    cardGroups: ["food", "directions"],
    showCard: {
      title: "Show this to the rider or staff",
      lines: ["你好，我不会说中文。", "请不要放辣，不要放花生。", "请放在酒店前台。", "到达时请打电话给我。", "谢谢！"],
    },
    planB: [
      "Walk to a restaurant nearby. Staff can point at the menu with you.",
      "Eat at the hotel restaurant or a convenience store (7-Eleven, Lawson, FamilyMart).",
      "Ask the front desk to order for you. They usually do this often.",
    ],
    trouble: [
      { p: "You cannot understand the rider", a: "Stop answering by voice. Send a text message in the app." },
      { p: "Food never arrived", a: "Open the order → Customer service and request a refund." },
      { p: "Wrong order", a: "Photograph it and report it in the app." },
      { p: "The food is too spicy", a: "Order again and write 不要辣 in the Notes." },
    ],
    sources: [],
  },

  {
    id: "sim",
    icon: "📶",
    title: { en: "SIM", zh: "电话卡", ja: "SIM", ko: "SIM" },
    subtitle: { en: "How to get online", zh: "怎么上网", ja: "通信を確保する", ko: "인터넷 연결하기" },
    category: { en: "Setup", zh: "准备", ja: "準備", ko: "준비" },
    priority: "P1",
    eta: { en: "5 min", zh: "5 分钟", ja: "5分", ko: "5분" },
    lastUpdated: "2026-09-23",
    task: "Get online in China with an eSIM or a local SIM card.",
    before: [
      "Phone that supports eSIM (or a SIM slot)",
      "Your passport",
      "A payment method",
    ],
    steps: [
      { t: "Decide: eSIM or local SIM", d: "eSIM is easier — buy before you fly and skip the shop. A local SIM gives you a Chinese number, which some apps ask for." },
      { t: "For an eSIM", d: "Buy from an international eSIM provider and install it before you leave home. Most data-only eSIMs cannot receive SMS." },
      { t: "For a local SIM", d: "Go to a China Mobile, China Unicom or China Telecom shop. Bring your passport. The staff registers it for you." },
      { t: "Expect the firewall", d: "Google, Gmail, WhatsApp, Instagram, Facebook and YouTube are blocked on local networks. Plan around this." },
      { t: "Test it before you leave the shop", d: "Check that data works and that a call goes through." },
      { t: "Top up when needed", d: "Use the carrier's app, Alipay, or go back to the shop." },
      { t: "Keep your home SIM active", d: "You may need it to receive verification codes from your bank." },
    ],
    mistakes: [
      { m: "Buying only at the airport", w: "Airport plans are usually more expensive", d: "Compare with a city shop, or buy an eSIM in advance" },
      { m: "Forgetting your passport", w: "The shop cannot register the SIM without it", d: "Always bring your passport" },
      { m: "Assuming your usual apps will work", w: "Many are blocked on local networks", d: "Set up your connectivity before you arrive" },
      { m: "Choosing a data-only eSIM and then needing SMS", w: "You cannot receive bank verification codes", d: "Keep your home number active for codes" },
    ],
    cardGroups: ["sim"],
    planB: [
      "Use hotel Wi-Fi for booking and messages.",
      "Turn on roaming from your home carrier for the first days.",
      "Ask the hotel front desk where to buy a SIM nearby.",
    ],
    trouble: [
      { p: "SIM does not work", a: "Restart the phone and check the APN settings. If it fails, go back to the shop." },
      { p: "You cannot receive SMS", a: "Data-only plans do not include SMS. Use your home number for codes." },
      { p: "You ran out of data", a: "Top up in the carrier app or the shop." },
    ],
    sources: [
      { label: "China Mobile", url: "https://www.chinamobileltd.com/" },
      { label: "China Unicom", url: "https://www.chinaunicom.com.hk/" },
    ],
    disclaimer: "SIM registration requires your passport — this is a legal requirement, not a shop policy. Which services are reachable on a local network is set by current regulation, and this page takes no position on it.",
  },

  {
    id: "emergency",
    icon: "🆘",
    title: { en: "Emergency", zh: "紧急求助", ja: "緊急", ko: "긴급" },
    subtitle: { en: "Get help fast", zh: "快速获得帮助", ja: "すぐに助けを求める", ko: "빠르게 도움받기" },
    category: { en: "Safety", zh: "安全", ja: "安全", ko: "안전" },
    priority: "P0",
    eta: { en: "now", zh: "立刻", ja: "今すぐ", ko: "즉시" },
    lastUpdated: "2026-09-23",
    task: "Get help fast when something goes wrong.",
    before: [
      "Know your location (a hotel name, metro station or landmark)",
      "Your passport, if you have it with you",
      "A charged phone, or a person nearby who can call for you",
    ],
    steps: [
      { t: "Call the right number", d: "110 police. 120 ambulance. 119 fire. 122 traffic accident. Operators may not speak English." },
      { t: "Get a Chinese speaker on the line", d: "Hand your phone to someone nearby, or show them 请帮我打 110。" },
      { t: "Give your location first", d: "Say the city, then the nearest landmark, hotel or metro station." },
      { t: "Keep your passport with you", d: "Police and hospitals ask for it." },
      { t: "Call your embassy if your passport is lost", d: "Save the number before you travel." },
      { t: "Ask the hotel front desk for help", d: "A 24-hour front desk can call, translate and write notes." },
    ],
    mistakes: [
      { m: "Calling 120 for a minor problem", w: "Ambulances are for emergencies", d: "Go to a hospital clinic for non-urgent care" },
      { m: "Not knowing your location", w: "Help takes much longer to arrive", d: "Screenshot your map location" },
      { m: "Leaving without your passport", w: "You cannot be registered or treated quickly", d: "Carry it, or keep a photo of it" },
    ],
    cardGroups: ["emergency", "lost", "phone", "hospital"],
    showCard: {
      title: "Show this to anyone nearby",
      lines: ["你好，我需要帮助。", "我不会说中文。", "请帮我打 110 / 120。", "我的位置是：[地点]", "谢谢！"],
    },
    planB: [
      "Ask any shop or mall staff member. Most will help you call.",
      "Use the in-app customer service in Alipay or your booking app.",
      "Go to the nearest large hotel and ask the front desk.",
    ],
    trouble: [
      { p: "Nobody understands you", a: "Show the card above. Keep it full screen." },
      { p: "Your phone is dead", a: "Ask to charge it at a shop, or use the phone battery card." },
      { p: "You lost your passport", a: "Report it to the police first, then go to your embassy with the police report." },
    ],
    sources: [
      { label: "China emergency numbers: 110 / 120 / 119 / 122", url: "https://www.gov.cn/" },
    ],
    disclaimer: "This page gives contact steps only. It is not legal, medical or safety advice.",
  },
];

/* ==========================================================================
   首次引导 —— 3 屏，讲清楚这个 App 怎么用
   最后一屏的 AI 入口是占位，后期直接替换成真正的问答界面。
   ========================================================================== */

const ONBOARDING = [
  {
    icon: "🧭",
    title: { en: "Pick what you need to do now", zh: "选你现在要做的事", ja: "今やることを選ぶ", ko: "지금 할 일을 고르세요" },
    body: {
      en: "The home screen is a list of tasks, not a menu. They are ordered the way you meet them — landing, getting online, paying, getting to your hotel.",
      zh: "首页是一串「任务」，不是菜单。顺序就是你会遇到的顺序 —— 落地、上网、支付、到酒店。",
      ja: "ホームはメニューではなく「やること」の一覧です。到着・通信・支払い・ホテルと、出会う順に並んでいます。",
      ko: "홈 화면은 메뉴가 아니라 '할 일' 목록입니다. 입국, 인터넷, 결제, 호텔 순서대로 배치되어 있습니다.",
    },
  },
  {
    icon: "🗣️",
    title: { en: "When words run out, show the screen", zh: "说不出来的时候，把屏幕递过去", ja: "言葉に詰まったら画面を見せる", ko: "말이 안 통하면 화면을 보여주세요" },
    body: {
      en: "Every step has a Chinese card. Tap it to open full screen — the Chinese is huge, so hand your phone straight to the person you are talking to.",
      zh: "每一步都配了中文卡片。点开就是全屏大字，直接把手机递给对方看就行。",
      ja: "各ステップに中国語カードがあります。タップすると全画面で大きく表示されるので、相手にそのまま渡してください。",
      ko: "모든 단계에 중국어 카드가 있습니다. 누르면 전체 화면으로 크게 보이니 상대방에게 그대로 건네세요.",
    },
  },
  {
    icon: "🆘",
    title: { en: "Emergency is always one tap away", zh: "紧急求助永远只差一次点击", ja: "緊急時はいつでも1タップ", ko: "긴급 상황은 언제나 한 번의 탭" },
    body: {
      en: "Police 110, ambulance 120, fire 119. The red card at the top of every page opens the emergency cards.",
      zh: "报警 110、急救 120、火警 119。每一页顶部都能一键打开紧急卡片。",
      ja: "警察110、救急120、消防119。どのページからも緊急カードを開けます。",
      ko: "경찰 110, 구급 120, 소방 119. 어느 페이지에서든 긴급 카드를 열 수 있습니다.",
    },
  },
  {
    icon: "🤖",
    title: { en: "Ask AI — coming soon", zh: "问 AI —— 敬请期待", ja: "AI に聞く — 準備中", ko: "AI에게 묻기 — 준비 중" },
    body: {
      en: "Later you will be able to just ask, in your own language. This screen is where that goes.",
      zh: "以后你可以直接用母语提问。这一屏就是它的位置。",
      ja: "将来は母語でそのまま質問できるようになります。この画面がその入口になります。",
      ko: "나중에는 모국어로 바로 물어볼 수 있게 됩니다. 이 화면이 그 자리입니다.",
    },
  },
];

/* ==========================================================================
   行前准备清单

   这份清单存在的理由：上面所有场景都是「落地之后」才读得到的，而落地时
   你多半没有网、没有现金、没有中文地址。这些问题只能在出发前解决，所以
   必须有一个「出发前」的页面，且它得是全 app 里最容易被找到的一页。

   顺序按你需要它的先后排，不按重要性排（护照 → 上网 → 离线 app → 支付
   → 地址 → 地图 → 电话）。
   ========================================================================== */

const PREP = [
  {
    id: "documents",
    icon: "🛂",
    title: { en: "Passport and visa in order", zh: "护照与签证先确认", ja: "パスポートとビザを確認", ko: "여권과 비자 확인" },
    body: {
      en: "Check your passport is valid for at least six months, and that your visa or visa-free entry covers your dates. Keep a photo of both on your phone.",
      zh: "确认护照有效期还有 6 个月以上，签证或免签入境覆盖你的行程日期。两样都在手机里存一张照片。",
      ja: "パスポートの残存期間が6か月以上あるか、ビザまたはビザ免除が渡航日をカバーしているか確認しましょう。両方ともスマホに写真を保存してください。",
      ko: "여권 유효기간이 6개월 이상인지, 비자나 무비자 입국이 여행 날짜를 포함하는지 확인하세요. 둘 다 휴대폰에 사진으로 저장해 두세요.",
    },
  },
  {
    id: "connectivity",
    icon: "📶",
    title: { en: "Plan how you will get online", zh: "想好落地怎么上网", ja: "到着後の通信手段を決めておく", ko: "도착 후 인터넷 사용 방법 정하기" },
    body: {
      en: "Buy an eSIM before you fly, or arrange roaming with your home carrier for the first day. Google, WhatsApp and Instagram are blocked on Chinese networks, so set up a workaround now rather than at the airport.",
      zh: "出发前买好 eSIM，或跟本国运营商开通漫游顶过第一天。中国网络屏蔽 Google、WhatsApp、Instagram —— 提前把方案准备好，别等到机场。",
      ja: "出発前に eSIM を買うか、初日は本国キャリアのローミングで凌ぎましょう。中国のネットワークでは Google、WhatsApp、Instagram が遮断されています。空港に着いてからではなく、今準備を。",
      ko: "출발 전에 eSIM을 사거나, 첫날은 자국 통신사 로밍으로 버티세요. 중국 네트워크에서는 Google, WhatsApp, Instagram이 차단됩니다. 공항에 도착한 뒤가 아니라 지금 준비하세요.",
    },
  },
  {
    id: "offline",
    icon: "📥",
    title: { en: "Open ChinaPASS once before you fly", zh: "出发前先打开一次 ChinaPASS", ja: "出発前に一度 ChinaPASS を開く", ko: "출발 전에 ChinaPASS를 한 번 열어 두기" },
    body: {
      en: "ChinaPASS works offline, but only after the first visit — the browser has to save it first. Open it at home, then add it to your home screen. Do this before you board, not after you land.",
      zh: "ChinaPASS 能离线用，但必须先访问过一次，浏览器才会把它存下来。在家打开一次，然后加到主屏幕。要在登机前做，不是落地后。",
      ja: "ChinaPASS はオフラインで使えますが、一度アクセスしないとブラウザが保存してくれません。自宅で開いて、ホーム画面に追加しておきましょう。搭乗前に。到着後ではなく。",
      ko: "ChinaPASS는 오프라인으로 쓸 수 있지만, 한 번 접속해야 브라우저가 저장합니다. 집에서 열고 홈 화면에 추가하세요. 탑승 전에요. 도착한 뒤가 아니라.",
    },
  },
  {
    id: "payment",
    icon: "💳",
    title: { en: "Set up a payment method", zh: "把支付方式设好", ja: "支払い方法を用意する", ko: "결제 수단 준비" },
    body: {
      en: "Install Alipay and add your own bank card. Verification takes a day or two, so start before you travel. Carry some cash as a backup — an ATM is the last resort if a card is refused.",
      zh: "装好支付宝并绑上本人的银行卡。实名认证要一两天，所以出发前就要弄。再带一些现金 —— 卡被拒时，ATM 是最后的退路。",
      ja: "Alipay を入れて本人名義の銀行カードを登録します。本人確認に1〜2日かかるので、出発前に始めてください。予備として現金も少し。カードが拒否されたときは ATM が最後の手段です。",
      ko: "Alipay를 설치하고 본인 명의 은행 카드를 등록하세요. 본인 인증에 하루이틀 걸리니 출발 전에 시작하세요. 예비로 현금도 조금 챙기세요. 카드가 거절되면 ATM이 마지막 수단입니다.",
    },
  },
  {
    id: "address",
    icon: "📍",
    title: { en: "Save your hotel address in Chinese", zh: "把酒店中文地址存下来", ja: "ホテルの住所を中国語で保存", ko: "호텔 주소를 중국어로 저장" },
    body: {
      en: "A driver cannot use the English name. Copy the Chinese address from your booking and save it as a screenshot you can show. Do this for every place you are staying.",
      zh: "司机看不懂英文名。从预订确认里复制中文地址，存成能给司机看的截图。每个住处都要存。",
      ja: "運転手は英語名では分かりません。予約確認から中国語の住所をコピーし、見せられるスクリーンショットで保存しましょう。滞在先ごとに。",
      ko: "기사는 영어 이름으로는 모릅니다. 예약 확인서에서 중국어 주소를 복사해 보여줄 수 있는 스크린샷으로 저장하세요. 묵는 곳마다.",
    },
  },
  {
    id: "maps",
    icon: "🗺️",
    title: { en: "Download offline maps", zh: "下好离线地图", ja: "オフライン地図をダウンロード", ko: "오프라인 지도 내려받기" },
    body: {
      en: "Download the city you are landing in, and pin your hotel. Your home maps app may not load without a connection, and local map apps are in Chinese.",
      zh: "把落地城市的地图下下来，标好酒店。本国的地图 app 没网可能打不开，而本地地图 app 是中文的。",
      ja: "到着する都市の地図を落として、ホテルをピン留めしましょう。母国の地図アプリは接続なしでは開けないことがあり、現地の地図アプリは中国語です。",
      ko: "도착하는 도시 지도를 받고 호텔을 표시해 두세요. 자국 지도 앱은 연결 없이 안 열릴 수 있고, 현지 지도 앱은 중국어입니다.",
    },
  },
  {
    id: "contacts",
    icon: "☎️",
    title: { en: "Save the numbers you might need", zh: "把可能用到的电话存好", ja: "必要になりそうな番号を保存", ko: "필요할 번호 저장" },
    body: {
      en: "Add your country's embassy or consulate in China, your travel insurance line, and one local contact. Police 110, ambulance 120, fire 119.",
      zh: "存好你国家驻华使领馆、旅行保险热线，和一个本地联系人。报警 110、急救 120、火警 119。",
      ja: "自国の在中国大使館・領事館、旅行保険の窓口、現地の連絡先を追加しましょう。警察110、救急120、消防119。",
      ko: "자국 주중 대사관·영사관, 여행자 보험 창구, 현지 연락처를 저장하세요. 경찰 110, 구급 120, 소방 119.",
    },
  },
];

/* ==========================================================================
   城市
   用内置经纬度包围盒离线匹配 —— 不调用任何第三方地理编码服务，
   坐标不出设备（docs/09 要求用户数据收集最小化）。
   ========================================================================== */

const CITY_BOXES = [
  { city: "Beijing",   zh: "北京",   ja: "北京",       ko: "베이징",     lat: [39.4, 41.1],  lng: [115.4, 117.5] },
  { city: "Shanghai",  zh: "上海",   ja: "上海",       ko: "상하이",     lat: [30.6, 31.9],  lng: [120.8, 122.1] },
  { city: "Guangzhou", zh: "广州",   ja: "広州",       ko: "광저우",     lat: [22.5, 23.9],  lng: [112.9, 114.1] },
  { city: "Shenzhen",  zh: "深圳",   ja: "深圳",       ko: "선전",       lat: [22.4, 22.9],  lng: [113.7, 114.6] },
  { city: "Chengdu",   zh: "成都",   ja: "成都",       ko: "청두",       lat: [30.0, 31.4],  lng: [103.0, 104.9] },
  { city: "Chongqing", zh: "重庆",   ja: "重慶",       ko: "충칭",       lat: [28.2, 32.2],  lng: [105.3, 110.2] },
  { city: "Xi'an",     zh: "西安",   ja: "西安",       ko: "시안",       lat: [33.7, 34.7],  lng: [107.7, 109.8] },
  { city: "Hangzhou",  zh: "杭州",   ja: "杭州",       ko: "항저우",     lat: [29.2, 30.6],  lng: [118.3, 120.8] },
  { city: "Nanjing",   zh: "南京",   ja: "南京",       ko: "난징",       lat: [31.0, 32.6],  lng: [118.3, 119.4] },
  { city: "Suzhou",    zh: "苏州",   ja: "蘇州",       ko: "쑤저우",     lat: [30.8, 32.1],  lng: [119.9, 121.4] },
  { city: "Wuhan",     zh: "武汉",   ja: "武漢",       ko: "우한",       lat: [29.9, 31.4],  lng: [113.7, 115.1] },
  { city: "Tianjin",   zh: "天津",   ja: "天津",       ko: "톈진",       lat: [38.5, 40.2],  lng: [116.7, 118.1] },
  { city: "Qingdao",   zh: "青岛",   ja: "青島",       ko: "칭다오",     lat: [35.6, 37.0],  lng: [119.5, 121.0] },
  { city: "Kunming",   zh: "昆明",   ja: "昆明",       ko: "쿤밍",       lat: [24.2, 26.3],  lng: [102.2, 103.4] },
  { city: "Xiamen",    zh: "厦门",   ja: "アモイ",     ko: "샤먼",       lat: [24.4, 24.9],  lng: [117.9, 118.4] },
  { city: "Harbin",    zh: "哈尔滨", ja: "ハルビン",   ko: "하얼빈",     lat: [44.4, 46.4],  lng: [125.7, 128.6] },
  { city: "Sanya",     zh: "三亚",   ja: "三亜",       ko: "싼야",       lat: [18.1, 18.5],  lng: [108.9, 109.7] },
  { city: "Guilin",    zh: "桂林",   ja: "桂林",       ko: "구이린",     lat: [24.6, 25.9],  lng: [109.6, 110.7] },
  { city: "Lhasa",     zh: "拉萨",   ja: "ラサ",       ko: "라싸",       lat: [29.2, 30.5],  lng: [90.4, 91.8] },
  { city: "Urumqi",    zh: "乌鲁木齐", ja: "ウルムチ", ko: "우루무치",   lat: [42.9, 44.5],  lng: [86.5, 88.5] },
];

const FAQ = [
  {
    q: { en: "My Alipay card was rejected. What now?",
         zh: "支付宝绑卡被拒了怎么办？",
         ja: "Alipayのカードが拒否されました。どうすれば？",
         ko: "알리페이 카드가 거절됐어요. 어떻게 하나요?" },
    a: { en: "Call your bank first. Many banks block China transactions by default. If the bank says it is fine, try a different card, or pay cash.",
         zh: "先给发卡行打电话 —— 很多银行默认拦截中国的交易。如果银行说没问题，换一张卡，或者用现金。",
         ja: "まずカード会社に電話してください。中国での取引を初期設定でブロックしている銀行が多いです。問題ないと言われたら、別のカードか現金を使ってください。",
         ko: "먼저 카드사에 전화하세요. 많은 은행이 중국 거래를 기본으로 차단합니다. 은행이 문제없다고 하면 다른 카드를 쓰거나 현금으로 결제하세요." },
  },
  {
    q: { en: "Can I use these apps without a Chinese phone number?",
         zh: "没有中国手机号能用这些 App 吗？",
         ja: "中国の電話番号がなくても使えますか？",
         ko: "중국 전화번호 없이도 쓸 수 있나요?" },
    a: { en: "Mostly yes. Alipay and 12306 accept international numbers for registration. Some services still ask for a Chinese number, so keep your home SIM active for SMS codes.",
         zh: "基本可以。支付宝和 12306 注册时都接受国际号码。但有些服务仍要中国号码，所以保留你本国的 SIM 卡用来收短信验证码。",
         ja: "ほぼ可能です。Alipayと12306は登録に海外番号を使えます。ただし中国番号を求めるサービスもあるので、SMS認証用に母国のSIMは有効にしておきましょう。",
         ko: "대부분 가능합니다. 알리페이와 12306은 등록에 해외 번호를 받습니다. 다만 중국 번호를 요구하는 서비스도 있으니, 문자 인증용으로 본국 SIM을 살려 두세요." },
  },
  {
    q: { en: "Can I buy a train ticket with my passport?",
         zh: "可以用护照买火车票吗？",
         ja: "パスポートで切符を買えますか？",
         ko: "여권으로 기차표를 살 수 있나요?" },
    a: { en: "Yes. Add your passport as a passenger in 12306. At the station, use the staffed lane instead of the automatic gate.",
         zh: "可以。在 12306 里把护照添加为乘车人。进站时走人工通道，不要走自助闸机。",
         ja: "はい。12306でパスポートを乗車人として登録します。駅では自動改札ではなく有人通路を使ってください。",
         ko: "네. 12306에서 여권을 승차자로 등록하세요. 역에서는 자동 개찰구 대신 직원이 있는 통로를 이용하세요." },
  },
  {
    q: { en: "Where do foreign cards not work?",
         zh: "外国卡在哪些地方刷不了？",
         ja: "海外カードが使えないのはどこ？",
         ko: "해외 카드가 안 되는 곳은 어디인가요?" },
    a: { en: "Small shops and street vendors often use personal QR transfers, which may not accept foreign cards. Carry some cash.",
         zh: "小商户和路边摊常用个人收款码，可能不支持外国卡。身上带些现金。",
         ja: "小さな店や露店は個人のQR送金を使うことが多く、海外カードが通らない場合があります。現金を持ち歩きましょう。",
         ko: "작은 가게나 노점은 개인 QR 송금을 쓰는 경우가 많아 해외 카드가 안 될 수 있습니다. 현금을 조금 들고 다니세요." },
  },
  {
    q: { en: "How do I reach a human customer service agent?",
         zh: "怎么找到人工客服？",
         ja: "有人のカスタマーサービスにはどう連絡しますか？",
         ko: "사람 상담원에게 어떻게 연락하나요?" },
    a: { en: "In Alipay: Me → Help Center → Contact us. Most agents handle English in the chat channel.",
         zh: "支付宝：我的 → 帮助中心 → 联系我们。文字客服一般都能用英文沟通。",
         ja: "Alipay：Me → ヘルプセンター → お問い合わせ。チャットなら英語対応の担当者がほとんどです。",
         ko: "알리페이: Me → 고객센터 → 문의하기. 채팅 상담은 대부분 영어로 응대합니다." },
  },
  {
    q: { en: "How do I get back something I left in a taxi?",
         zh: "东西落在出租车上了怎么找回来？",
         ja: "タクシーに忘れ物をしたら？",
         ko: "택시에 두고 내린 물건은 어떻게 찾나요?" },
    a: { en: "Open the order in DiDi → Contact driver → Lost item. If the driver does not reply, use the app's feedback form.",
         zh: "在滴滴里打开订单 → 联系司机 → 遗失物品。司机不回就用 App 的意见反馈。",
         ja: "DiDiで注文を開く → 運転手に連絡 → 忘れ物。返信がなければアプリのフィードバックから連絡してください。",
         ko: "디디에서 주문을 열고 → 기사에게 연락 → 분실물. 기사가 답이 없으면 앱의 피드백 양식을 이용하세요." },
  },
  {
    q: { en: "Do I need a VPN?",
         zh: "我需要 VPN 吗？",
         ja: "VPNは必要ですか？",
         ko: "VPN이 필요한가요?" },
    a: { en: "Many international services are blocked on local networks. If you need them, set up your own connectivity before you arrive. Rules apply — check current regulations.",
         zh: "很多国际服务在本地网络访问不了。如果需要，请在出发前准备好你自己的连接方式。相关规定请以现行法规为准。",
         ja: "多くの海外サービスは現地回線でブロックされています。必要な場合は渡航前にご自身で接続手段を用意してください。現行の規定を確認してください。",
         ko: "많은 해외 서비스가 현지 회선에서 차단됩니다. 필요하다면 출국 전에 본인의 연결 수단을 준비하세요. 현행 규정을 확인하세요." },
  },
];
